import { NextRequest } from 'next/server';
import { GoogleGenAI } from "@google/genai";
import { getLastUsedApi, setLastUsedApi } from '@/lib/config-store';

interface GroqMessage {
  role: string;
  content: string;
}

interface GroqPayload {
  model: string;
  messages: GroqMessage[];
  temperature?: number;
  top_p?: number;
}

// Retrofitted LLM fetcher supporting both Groq and Gemini APIs
async function fetchLLM(
  provider: "gemini" | "groq",
  body: GroqPayload,
  apiKey: string,
  log?: (msg: string) => void
) {
  if (provider === "gemini") {
    log?.(`[API TRANSITION]: Directing task to Gemini...`);
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY is missing on server-side secrets configuration.");
    }
    
    const ai = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: { "User-Agent": "aistudio-build" }
      }
    });

    // Map system prompts and conversation to Gemini-compatible format
    const systemMessage = body.messages.find(m => m.role === "system");
    const otherMessages = body.messages.filter(m => m.role !== "system");

    const contents = otherMessages.map(m => ({
      role: m.role === "assistant" ? "model" : "user",
      parts: [{ text: m.content }]
    }));

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents,
      config: {
        systemInstruction: systemMessage?.content,
        temperature: body.temperature ?? 0.7,
        topP: body.top_p ?? 0.9,
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response content generated by Gemini.");
    }

    log?.(`Gemini API call successful.`);
    
    // Return standard payload for seamless downstream parsing
    return {
      choices: [{
        message: {
          content: text
        }
      }],
      usage: {
        prompt_tokens: Math.round(JSON.stringify(contents).length / 4),
        completion_tokens: Math.round(text.length / 4)
      }
    };
  } else {
    // Groq fetcher
    return fetchGroq(body, apiKey, log);
  }
}

async function fetchGroq(body: GroqPayload, apiKey: string, log?: (msg: string) => void) {
  const url = 'https://api.groq.com/openai/v1/chat/completions';
  const delays = [2000, 4000, 8000];
  
  for (let attempt = 0; attempt <= 3; attempt++) {
    const res = await fetch(url, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(body)
    });
    
    if (res.status === 429) {
      if (attempt < 3) {
        log?.(`Groq API rate limit hit (HTTP 429). Retrying in ${delays[attempt]/1000}s (Attempt ${attempt + 1}/3)...`);
        await new Promise((r) => setTimeout(r, delays[attempt]));
        continue;
      } else {
        log?.(`Groq API failed after 3 retries.`);
      }
    }
    
    if (!res.ok) {
      const errorText = await res.text();
      log?.(`Groq API Error: ${res.status} - ${errorText}`);
      throw new Error(`Groq API Error: ${res.status} - ${errorText}`);
    }
    
    log?.(`Groq API call successful.`);
    return res.json();
  }
}

async function commitToGithub(trainingDataStr: string, commitMessage: string, contextMsg: string, githubRepo: string, githubPath: string, githubPat: string, log: (msg: string) => void) {
  log(`Committing data for ${contextMsg}...`);
  const githubApiUrl = `https://api.github.com/repos/${githubRepo}/contents/${githubPath}`;
  
  try {
    const getFileRes = await fetch(githubApiUrl, {
      headers: {
        'Authorization': `token ${githubPat}`,
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'Synthetic-Data-Generator'
      }
    });
    
    let existingContent = "";
    let sha: string | undefined = undefined;
    
    if (getFileRes.ok) {
      const fileData = await getFileRes.json();
      sha = fileData.sha;
      existingContent = Buffer.from(fileData.content, 'base64').toString('utf-8');
    } else if (getFileRes.status !== 404) {
      throw new Error(`GitHub API Error during GET: ${getFileRes.status} - ${await getFileRes.text()}`);
    }
    
    const newContent = existingContent + (existingContent && !existingContent.endsWith('\n') ? '\n' : '') + trainingDataStr + '\n';
    const newContentBase64 = Buffer.from(newContent, 'utf-8').toString('base64');
    
    const putFileRes = await fetch(githubApiUrl, {
      method: 'PUT',
      headers: {
        'Authorization': `token ${githubPat}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'Synthetic-Data-Generator'
      },
      body: JSON.stringify({
        message: commitMessage,
        content: newContentBase64,
        sha: sha
      })
    });
    
    if (!putFileRes.ok) {
      throw new Error(`GitHub PUT Error: ${putFileRes.status} - ${await putFileRes.text()}`);
    }
    log(`Commit successful.`);
  } catch (error: any) {
    log(`Commit failed: ${error.message}`);
    throw error;
  }
}

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { 
    target_topic, 
    massive_context, 
    synthesis_angles, 
    groq_key, 
    github_token, 
    target_repo, 
    file_path,
    synthesis_mode,
    synthesisMode,
    api_provider, // Client can send selected api: "gemini" or "groq"
    debate_rounds_mode, // "manual" or "auto"
    debate_rounds // manual number of rounds
  } = body;

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      function log(message: string) {
        const time = new Date().toLocaleTimeString();
        controller.enqueue(encoder.encode(`data: [${time}] - ${message}\n\n`));
      }

      const runStats = {
        apiCalls: 0,
        promptTokens: 0,
        completionTokens: 0,
        cost: 0,
        completedAngles: 0,
        completedRounds: 0,
        totalCompletions: 0
      };

      function logStats() {
        controller.enqueue(encoder.encode(`data: [STATS] - ${JSON.stringify(runStats)}\n\n`));
      }

      try {
        log("Initialization started... Orchestrating environment.");
        
        if (!target_topic || !massive_context || !github_token || !target_repo || !file_path) {
          throw new Error("Missing required configuration fields.");
        }

        // Active API selection logic & Environment preservation
        const activeApi = api_provider || getLastUsedApi() || "gemini";
        setLastUsedApi(activeApi);
        log(`Active API Environment: ${activeApi.toUpperCase()} (Remembered for seamless future completions)`);

        let selectedApiKey = "";
        if (activeApi === "gemini") {
          selectedApiKey = process.env.GEMINI_API_KEY || "";
          if (!selectedApiKey) {
            throw new Error("GEMINI_API_KEY is not configured in secrets. Please set it in Settings.");
          }
        } else {
          selectedApiKey = groq_key;
          if (!selectedApiKey) {
            throw new Error("Groq API key is required when running in Groq mode.");
          }
        }

        // Debate round selection logic
        let calculatedRounds = 3;
        if (debate_rounds_mode === "auto") {
          const wordCount = massive_context.trim().split(/\s+/).length;
          if (wordCount < 100) {
            calculatedRounds = 2;
          } else if (wordCount < 300) {
            calculatedRounds = 3;
          } else if (wordCount < 600) {
            calculatedRounds = 4;
          } else {
            calculatedRounds = 5;
          }
          log(`[DEBATE AUTO-SELECT]: Evaluated context complexity (${wordCount} words). Dynamically allocated ${calculatedRounds} debate rounds for deep exploration.`);
        } else {
          calculatedRounds = Math.max(1, Math.min(10, Number(debate_rounds) || 3));
          log(`[DEBATE MANUAL]: Running standard ${calculatedRounds} configured debate rounds.`);
        }

        const mode = synthesis_mode || synthesisMode || "balanced";
        let temperature = 0.6;
        let top_p = 0.9;
        if (mode === "exploratory") {
          temperature = 0.9;
          top_p = 0.95;
        } else if (mode === "rigorous") {
          temperature = 0.2;
          top_p = 0.8;
        }
        log(`Using Synthesis Mode: ${mode.toUpperCase()} (Temp: ${temperature}, Top_P: ${top_p})`);

        let existingAngles: string[] = [];
        let completedDebateRounds = 0;
        const debateHistory: GroqMessage[] = [];

        log("Checking remote storage on GitHub for existing state...");
        const githubApiUrl = `https://api.github.com/repos/${target_repo}/contents/${file_path}`;
        try {
          const getFileRes = await fetch(githubApiUrl, {
            headers: {
              'Authorization': `token ${github_token}`,
              'Accept': 'application/vnd.github.v3+json',
              'User-Agent': 'Synthetic-Data-Generator'
            }
          });

          if (getFileRes.ok) {
            const fileData = await getFileRes.json();
            const existingContent = Buffer.from(fileData.content, 'base64').toString('utf-8');
            const lines = existingContent.split('\n').filter(Boolean);
            
            for (const line of lines) {
              try {
                const parsed = JSON.parse(line);
                if (parsed && Array.isArray(parsed.messages)) {
                  runStats.totalCompletions++;
                  // Metadata detection
                  if (parsed.metadata) {
                    if (parsed.metadata.phase === 1 && parsed.metadata.angle) {
                      existingAngles.push(parsed.metadata.angle);
                    } else if (parsed.metadata.phase === 2) {
                      completedDebateRounds++;
                      const msgs = parsed.messages;
                      const questionMsg = msgs[msgs.length - 2];
                      const answerMsg = msgs[msgs.length - 1];
                      if (questionMsg && answerMsg) {
                        debateHistory.push({ role: "user", content: questionMsg.content });
                        debateHistory.push({ role: "assistant", content: answerMsg.content });
                      }
                    }
                  } else {
                    // Fallback content-based detection
                    const userMsg = parsed.messages.find((m: any) => m.role === 'user' && typeof m.content === 'string' && m.content.includes("perspective of:"));
                    if (userMsg) {
                      const match = userMsg.content.match(/perspective of:\s*([^.]+)/);
                      if (match && match[1]) {
                        existingAngles.push(match[1].trim());
                      }
                    } else {
                      const isDebate = parsed.messages.some((m: any) => m.role === 'system' && typeof m.content === 'string' && m.content.includes("interrogating a master model"));
                      if (isDebate) {
                        completedDebateRounds++;
                        const msgs = parsed.messages;
                        const questionMsg = msgs[msgs.length - 2];
                        const answerMsg = msgs[msgs.length - 1];
                        if (questionMsg && answerMsg) {
                          debateHistory.push({ role: "user", content: questionMsg.content });
                          debateHistory.push({ role: "assistant", content: answerMsg.content });
                        }
                      }
                    }
                  }
                }
              } catch (e) {
                // Ignore individual parsing errors
              }
            }
            runStats.completedAngles = existingAngles.length;
            runStats.completedRounds = completedDebateRounds;
            logStats();
            log(`Detected existing progress: ${existingAngles.length} angles synthesized, ${completedDebateRounds} debate rounds completed.`);
          } else if (getFileRes.status === 404) {
            log("No existing dataset file found on GitHub. Starting a fresh run.");
          } else {
            log(`Could not verify existing state (GitHub status ${getFileRes.status}). Proceeding fresh.`);
          }
        } catch (error: any) {
          log(`Error querying remote state: ${error.message}. Proceeding fresh.`);
        }

        const angles = ["Technical Constraints", "Operational Logic", "Edge Cases", "Structural Limitations", "Failures"];
        const selectedAngles = angles.slice(0, Math.min(synthesis_angles, angles.length));
        
        // Phase 1: 360-Degree Synthesis
        for (let i = 0; i < selectedAngles.length; i++) {
          const angle = selectedAngles[i];
          if (existingAngles.includes(angle)) {
            log(`Phase 1 - Angle ${i + 1}: ${angle} already exists on GitHub. Skipping.`);
            continue;
          }
          log(`Phase 1 - Injecting Angle ${i + 1}: ${angle}...`);
          
          const teacherSystemPrompt = `You are an elite research professor specializing in ${target_topic}. You are examining text materials from a 360-degree viewpoint. Your answers must be incredibly comprehensive, technically deep, and strictly grounded in the following provided reference text context: ${massive_context}. Do not invent outside facts.`;
          
          const anglePrompt = `Analyze the topic from the perspective of: ${angle}. Provide a detailed analysis based solely on the reference text.`;
        
          const messages = [
            { role: "system", content: teacherSystemPrompt },
            { role: "user", content: anglePrompt }
          ];
        
          const response = await fetchLLM(
            activeApi,
            {
              model: "llama-3.3-70b-versatile",
              messages,
              temperature,
              top_p
            },
            selectedApiKey,
            log
          );
        
          const teacherAnswer = response.choices[0].message.content;
          
          // Update Stats
          if (response?.usage) {
            const pTokens = response.usage.prompt_tokens || 0;
            const cTokens = response.usage.completion_tokens || 0;
            runStats.apiCalls += 1;
            runStats.promptTokens += pTokens;
            runStats.completionTokens += cTokens;
            // Weighted cost projection depending on provider
            const multiplier = activeApi === "gemini" ? 0.075 : 0.59;
            runStats.cost += (pTokens * multiplier + cTokens * (multiplier * 1.3)) / 1000000;
            runStats.completedAngles++;
            runStats.totalCompletions++;
            logStats();
          }
          
          const dataStr = JSON.stringify({ messages: [...messages, { role: "assistant", content: teacherAnswer }], metadata: { phase: 1, angle } });
          await commitToGithub(dataStr, `Append synthesis for angle: ${angle}`, `angle ${angle}`, target_repo, file_path, github_token, log);
          
          log(`Phase 1 - Angle ${i + 1} completed.`);
        }
        
        // Phase 2: Autonomous Debate
        log(`Phase 2 - Initiating Autonomous Debate (Student vs Teacher)...`);
        const studentSystemPrompt = `You are an inquisitive junior AI agent tasked with rigorously interrogating a master model about ${target_topic}. Review the prior explanation provided by the teacher, locate any abstract concepts, gaps in operational logic, or complex implementations, and generate the next sharp, analytical question to dig deeper.`;
        
        const teacherDebateSystemPrompt = `You are an elite research professor specializing in ${target_topic}. Your answers must be incredibly comprehensive, technically deep, and strictly grounded in the context provided earlier.`;
        
        for (let r = 0; r < calculatedRounds; r++) {
            if (r < completedDebateRounds) {
                log(`Phase 2 - Debate Round ${r + 1} already exists on GitHub. Skipping.`);
                continue;
            }
            log(`Phase 2 - Debate Round ${r + 1}: Student is processing...`);
            
            const studentMessages = [
                { role: "system", content: studentSystemPrompt },
                { role: "user", content: `Context: ${massive_context}\nGenerate a sharp, analytical question based on the context.` }
            ];
            
            if (debateHistory.length > 0) {
                studentMessages.push({ role: "assistant", content: "I have asked previously: " + debateHistory.filter((m: GroqMessage) => m.role === 'user').map((m: GroqMessage) => m.content).join("\n") });
                studentMessages.push({ role: "user", content: "Based on the teacher's last answer, what is your next analytical question?" });
            }
        
            const studentResponse = await fetchLLM(
                activeApi,
                {
                  model: "llama-3.1-8b-instant",
                  messages: studentMessages
                },
                selectedApiKey,
                log
            );
        
            const question = studentResponse.choices[0].message.content;
            
            // Update Stats for Student
            if (studentResponse?.usage) {
              const pTokens = studentResponse.usage.prompt_tokens || 0;
              const cTokens = studentResponse.usage.completion_tokens || 0;
              runStats.apiCalls += 1;
              runStats.promptTokens += pTokens;
              runStats.completionTokens += cTokens;
              const multiplier = activeApi === "gemini" ? 0.075 : 0.05;
              runStats.cost += (pTokens * multiplier + cTokens * (multiplier * 1.5)) / 1000000;
              logStats();
            }

            log(`Phase 2 - Student asks: "${question.substring(0, 70).replace(/\n/g, ' ')}..."`);
            
            log(`Phase 2 - Teacher is synthesizing response...`);
            const teacherMessages = [
                { role: "system", content: teacherDebateSystemPrompt },
                { role: "user", content: `Here is the reference context: ${massive_context}` },
                ...debateHistory,
                { role: "user", content: question }
            ];
        
            const teacherResponse = await fetchLLM(
                activeApi,
                {
                  model: "llama-3.3-70b-versatile",
                  messages: teacherMessages,
                  temperature,
                  top_p
                },
                selectedApiKey,
                log
            );
        
            const answer = teacherResponse.choices[0].message.content;
            
            // Update Stats for Teacher
            if (teacherResponse?.usage) {
              const pTokens = teacherResponse.usage.prompt_tokens || 0;
              const cTokens = teacherResponse.usage.completion_tokens || 0;
              runStats.apiCalls += 1;
              runStats.promptTokens += pTokens;
              runStats.completionTokens += cTokens;
              const multiplier = activeApi === "gemini" ? 0.075 : 0.59;
              runStats.cost += (pTokens * multiplier + cTokens * (multiplier * 1.3)) / 1000000;
              runStats.completedRounds++;
              runStats.totalCompletions++;
              logStats();
            }

            debateHistory.push({ role: "user", content: question });
            debateHistory.push({ role: "assistant", content: answer });
            
            const dataStr = JSON.stringify({ messages: [...teacherMessages, { role: "assistant", content: answer }], metadata: { phase: 2, round: r + 1 } });
            await commitToGithub(dataStr, `Append debate round ${r + 1}`, `debate round ${r + 1}`, target_repo, file_path, github_token, log);
            
            log(`Phase 2 - Debate Round ${r + 1} completed.`);
        }
        
        log(`PROCESS COMPLETE! Dataset successfully appended to GitHub.`);
        controller.close();
      } catch (error: any) {
        log(`SYSTEM ERROR: ${error.message}`);
        controller.close();
      }
    }
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
    },
  });
}
